USE ht;
LOCK TABLES `collection_names` WRITE;
/*!40000 ALTER TABLE `collection_names` DISABLE KEYS */;
INSERT INTO `collection_names` VALUES ('AEU','University of Alberta');
INSERT INTO `collection_names` VALUES ('AUBRU','The University of Queensland');
INSERT INTO `collection_names` VALUES ('AZTES','Arizona State University');
INSERT INTO `collection_names` VALUES ('CHI','University of Chicago');
INSERT INTO `collection_names` VALUES ('COO','Cornell University');
INSERT INTO `collection_names` VALUES ('CTU','University of Connecticut');
INSERT INTO `collection_names` VALUES ('DEU','University of Delaware');
INSERT INTO `collection_names` VALUES ('FMU','University of Miami');
INSERT INTO `collection_names` VALUES ('GEU','Emory University');
INSERT INTO `collection_names` VALUES ('GRI','Getty Research Institute');
INSERT INTO `collection_names` VALUES ('GWLA','Technical Report Archive &amp; Image Library');
INSERT INTO `collection_names` VALUES ('HVD','Harvard University');
INSERT INTO `collection_names` VALUES ('IAU','University of Iowa');
INSERT INTO `collection_names` VALUES ('IBC','Boston College');
INSERT INTO `collection_names` VALUES ('IDUKE','Duke University');
INSERT INTO `collection_names` VALUES ('ILOC','Library of Congress');
INSERT INTO `collection_names` VALUES ('INCSU','North Carolina State University');
INSERT INTO `collection_names` VALUES ('INNC','Columbia University');
INSERT INTO `collection_names` VALUES ('INND','University of Notre Dame');
INSERT INTO `collection_names` VALUES ('INRLF','University of California');
INSERT INTO `collection_names` VALUES ('INU','Indiana University');
INSERT INTO `collection_names` VALUES ('IPST','Pennsylvania State University');
INSERT INTO `collection_names` VALUES ('ISRLF','University of California');
INSERT INTO `collection_names` VALUES ('IUCD','University of California');
INSERT INTO `collection_names` VALUES ('IUCLA','University of California');
INSERT INTO `collection_names` VALUES ('IUFL','State University System of Florida');
INSERT INTO `collection_names` VALUES ('IUIUC','University of Illinois at Urbana-Champaign');
INSERT INTO `collection_names` VALUES ('IUNC','University of North Carolina at Chapel Hill');
INSERT INTO `collection_names` VALUES ('KEIO','Keio University');
INSERT INTO `collection_names` VALUES ('LEBAU','American University of Beirut');
INSERT INTO `collection_names` VALUES ('MDBJ','Johns Hopkins University');
INSERT INTO `collection_names` VALUES ('MDL','Minnesota Digital Library');
INSERT INTO `collection_names` VALUES ('MDU','University of Maryland, College Park');
INSERT INTO `collection_names` VALUES ('MIU','University of Michigan');
INSERT INTO `collection_names` VALUES ('MMET','Tufts University');
INSERT INTO `collection_names` VALUES ('MOU','University of Missouri - Columbia');
INSERT INTO `collection_names` VALUES ('MSU','Michigan State University');
INSERT INTO `collection_names` VALUES ('MU','University of Massachusetts Amherst');
INSERT INTO `collection_names` VALUES ('MWICA','Sterling and Francine Clark Art Institute');
INSERT INTO `collection_names` VALUES ('NBB','Brooklyn Museum');
INSERT INTO `collection_names` VALUES ('NBUU','University At Buffalo, The State University of New York');
INSERT INTO `collection_names` VALUES ('NCWSW','Wake Forest University');
INSERT INTO `collection_names` VALUES ('NJP','Princeton University');
INSERT INTO `collection_names` VALUES ('NNC','Columbia University');
INSERT INTO `collection_names` VALUES ('NNFR','The Frick Collection');
INSERT INTO `collection_names` VALUES ('NRLF','University of California');
INSERT INTO `collection_names` VALUES ('NWU','Northwestern University');
INSERT INTO `collection_names` VALUES ('NYP','New York Public Library');
INSERT INTO `collection_names` VALUES ('OKS','Oklahoma State University');
INSERT INTO `collection_names` VALUES ('OSU','The Ohio State University');
INSERT INTO `collection_names` VALUES ('PHC','Haverford College');
INSERT INTO `collection_names` VALUES ('PPT','Temple University');
INSERT INTO `collection_names` VALUES ('PST','Pennsylvania State University');
INSERT INTO `collection_names` VALUES ('PU','University of Pennsylvania');
INSERT INTO `collection_names` VALUES ('PUR','Purdue University');
INSERT INTO `collection_names` VALUES ('QMM','McGill University');
INSERT INTO `collection_names` VALUES ('SCU','University of South Carolina');
INSERT INTO `collection_names` VALUES ('SRLF','University of California');
INSERT INTO `collection_names` VALUES ('TXCM','Texas A&amp;M University');
INSERT INTO `collection_names` VALUES ('TXSMTSU','Texas State University - San Marcos');
INSERT INTO `collection_names` VALUES ('TXU','The University of Texas');
INSERT INTO `collection_names` VALUES ('UCBK','University of California');
INSERT INTO `collection_names` VALUES ('UCD','University of California');
INSERT INTO `collection_names` VALUES ('UCI','University of California');
INSERT INTO `collection_names` VALUES ('UCLA','University of California');
INSERT INTO `collection_names` VALUES ('UCM','Universidad Complutense de Madrid');
INSERT INTO `collection_names` VALUES ('UCMR','University of California');
INSERT INTO `collection_names` VALUES ('UCR','University of California');
INSERT INTO `collection_names` VALUES ('UCSB','University of California');
INSERT INTO `collection_names` VALUES ('UCSC','University of California');
INSERT INTO `collection_names` VALUES ('UCSD','University of California');
INSERT INTO `collection_names` VALUES ('UCSF','University of California');
INSERT INTO `collection_names` VALUES ('UFDC','State University System of Florida');
INSERT INTO `collection_names` VALUES ('UIUC','University of Illinois at Urbana-Champaign');
INSERT INTO `collection_names` VALUES ('UIUCL','University of Illinois at Urbana-Champaign');
INSERT INTO `collection_names` VALUES ('UKLOKU','Knowledge Unlatched');
INSERT INTO `collection_names` VALUES ('UMBUS','University of Michigan');
INSERT INTO `collection_names` VALUES ('UMDB','University of Michigan');
INSERT INTO `collection_names` VALUES ('UMDCMP','Millennium Project');
INSERT INTO `collection_names` VALUES ('UMLAW','University of Michigan');
INSERT INTO `collection_names` VALUES ('UMN','University of Minnesota');
INSERT INTO `collection_names` VALUES ('UMPRIVATE','Private Donor');
INSERT INTO `collection_names` VALUES ('USU','Utah State University Press');
INSERT INTO `collection_names` VALUES ('UUHHS','Unitarian Universalist History and Heritage Society');
INSERT INTO `collection_names` VALUES ('UVA','University of Virginia');
INSERT INTO `collection_names` VALUES ('VIRCU','Virginia Commonwealth University');
INSERT INTO `collection_names` VALUES ('WAU','University of Washington');
INSERT INTO `collection_names` VALUES ('WU','University of Wisconsin - Madison');
INSERT INTO `collection_names` VALUES ('YALE','Yale University');
/*!40000 ALTER TABLE `collection_names` ENABLE KEYS */;
UNLOCK TABLES;

