USE ht;
LOCK TABLES `reasons` WRITE;
/*!40000 ALTER TABLE `reasons` DISABLE KEYS */;
INSERT INTO `reasons` VALUES (1,'bib','bibliographically-derived by automatic processes');
INSERT INTO `reasons` VALUES (2,'ncn','no printed copyright notice');
INSERT INTO `reasons` VALUES (3,'con','contractual agreement with copyright holder on file');
INSERT INTO `reasons` VALUES (4,'ddd','due diligence documentation on file');
INSERT INTO `reasons` VALUES (5,'man','manual access control override; see note for details');
INSERT INTO `reasons` VALUES (6,'pvt','private personal information visible');
INSERT INTO `reasons` VALUES (7,'ren','copyright renewal research was conducted');
INSERT INTO `reasons` VALUES (8,'nfi','needs further investigation (copyright research partially complete, and an ambiguous, unclear, or other time-consuming situation was encountered)');
INSERT INTO `reasons` VALUES (9,'cdpp','title page or verso contain copyright date and/or place of publication information not in bib record');
INSERT INTO `reasons` VALUES (10,'ipma','in-print and market availability research was conducted');
INSERT INTO `reasons` VALUES (11,'unp','unpublished work');
INSERT INTO `reasons` VALUES (12,'gfv','Google viewability set at VIEW_FULL');
INSERT INTO `reasons` VALUES (13,'crms','derived from multiple reviews in the Copyright Review Management System (CRMS) via an internal resolution policy; consult CRMS records for details');
INSERT INTO `reasons` VALUES (14,'add','author death date research was conducted or notification was received from authoritative source');
INSERT INTO `reasons` VALUES (15,'exp','expiration of copyright term for non-US work with corporate author');
INSERT INTO `reasons` VALUES (16,'del','deleted from the repository; see note for details');
INSERT INTO `reasons` VALUES (17,'gatt','non-US public domain work restored to in-copyright in the US by GATT');
INSERT INTO `reasons` VALUES (18,'supp','suppressed from view; see note for details');
/*!40000 ALTER TABLE `reasons` ENABLE KEYS */;
UNLOCK TABLES;
