USE ht;
LOCK TABLES `sources` WRITE;
/*!40000 ALTER TABLE `sources` DISABLE KEYS */;
INSERT INTO `sources` VALUES (1,'google','Google',2,'google');
INSERT INTO `sources` VALUES (2,'lit-dlps-dc','University of Michigan Library IT, Digital Library Production Service, Digital Conversion',1,'umich*;umdl-umich');
INSERT INTO `sources` VALUES (3,'ump','University of Michigan Press',3,'umich;press-umich*');
INSERT INTO `sources` VALUES (4,'ia','Internet Archive',1,'archive');
INSERT INTO `sources` VALUES (5,'yale','Yale University (with support from Microsoft)',1,'yale;ht_support-microsoft*');
INSERT INTO `sources` VALUES (6,'mdl','Minnesota Digital Library',4,'mndigital');
INSERT INTO `sources` VALUES (7,'mhs','Minnesota Historical Society',4,'mnhs');
INSERT INTO `sources` VALUES (8,'usup','Utah State University Press',3,'usupress');
INSERT INTO `sources` VALUES (9,'ucm','Universidad Complutense de Madrid',1,'ucm');
INSERT INTO `sources` VALUES (10,'purd','Purdue University',1,'purdue');
INSERT INTO `sources` VALUES (11,'getty','Getty Research Institute',1,'getty');
INSERT INTO `sources` VALUES (12,'um-dc-mp','University of Michigan, Duderstadt Center, Millennium Project',1,'umich;milproj-dc-umich*');
INSERT INTO `sources` VALUES (13,'uiuc','University of Illinois at Urbana-Champaign',1,'illinois');
INSERT INTO `sources` VALUES (14,'brooklynmuseum','Brooklyn Museum',1,'brooklynmuseum');
INSERT INTO `sources` VALUES (15,'uf','State University System of Florida',1,'flbog');
INSERT INTO `sources` VALUES (16,'tamu','Texas A&M',1,'tamu');
INSERT INTO `sources` VALUES (17,'udel','University of Delaware',1,'udel');
INSERT INTO `sources` VALUES (18,'private','Private Donor',1,'ht_private');
INSERT INTO `sources` VALUES (19,'umich','University of Michigan (Other)',1,'umich');
INSERT INTO `sources` VALUES (20,'clark','Clark Art Institute',1,'clarkart');
INSERT INTO `sources` VALUES (21,'ku','Knowledge Unlatched',1,'knowledgeunlatched');
INSERT INTO `sources` VALUES (22,'mcgill','McGill University',1,'mcgill');
INSERT INTO `sources` VALUES (23,'bc','Boston College',1,'bc');
INSERT INTO `sources` VALUES (24,'nnc','Columbia University',1,'columbia');
INSERT INTO `sources` VALUES (25,'geu','Emory University',1,'emory');
INSERT INTO `sources` VALUES (26,'borndigital','Born Digital (placeholder)',1,NULL);
INSERT INTO `sources` VALUES (27,'yale2','Yale University',1,'yale');
INSERT INTO `sources` VALUES (28,'mou','University of Missouri',1,'missouri');
INSERT INTO `sources` VALUES (29,'chtanc','National Central Library of Taiwan',1,'washington;ncl');
INSERT INTO `sources` VALUES (30,'bentley-umich','Bentley Historical Library, University of Michigan',1,'umich*;bentley-umich');
INSERT INTO `sources` VALUES (31,'clements-umich','William L. Clements Library, University of Michigan',1,'umich*;clements-umich');
INSERT INTO `sources` VALUES (32,'wau','University of Washington',1,'washington');
INSERT INTO `sources` VALUES (33,'cornell','Cornell University',1,'cornell');
INSERT INTO `sources` VALUES (34,'cornell-ms','Cornell University (with support from Microsoft)',1,'cornell*;ht_support-microsoft');
INSERT INTO `sources` VALUES (35,'umd','University of Maryland',1,'umd');
INSERT INTO `sources` VALUES (36,'frick','The Frick Collection',1,'frick');
INSERT INTO `sources` VALUES (37,'northwestern','Northwestern University',1,'northwestern');
INSERT INTO `sources` VALUES (38,'umn','University of Minnesota',1,'umn');
INSERT INTO `sources` VALUES (39,'berkeley','University of California, Berkeley',1,'berkeley');
INSERT INTO `sources` VALUES (40,'ucmerced','University of California, Merced',1,'ucmerced');
INSERT INTO `sources` VALUES (41,'nd','University of Notre Dame',1,'nd');
INSERT INTO `sources` VALUES (42,'princeton','Princeton University',1,'princeton');
INSERT INTO `sources` VALUES (43,'uq','The University of Queensland',1,'uq');
INSERT INTO `sources` VALUES (44,'ucla','University of California, Los Angeles',1,'ucla');
INSERT INTO `sources` VALUES (45,'osu','The Ohio State University',1,'osu');
INSERT INTO `sources` VALUES (46,'upenn','University of Pennsylvania',1,'upenn');
INSERT INTO `sources` VALUES (47,'aub','American University of Beirut',1,'aub');
INSERT INTO `sources` VALUES (48,'ucsd','University of California San Diego',1,'ucsd');
INSERT INTO `sources` VALUES (49,'harvard','Harvard University',1,'harvard');
INSERT INTO `sources` VALUES (50,'miami','University of Miami',1,'miami');
INSERT INTO `sources` VALUES (51,'vcu','Virginia Commonwealth University',1,'vcu');
INSERT INTO `sources` VALUES (52,'jhu','Johns Hopkins University',1,'jhu');
INSERT INTO `sources` VALUES (53,'haverford','Haverford College',1,'haverford');
INSERT INTO `sources` VALUES (54,'asu','Arizona State University',1,'asu');
INSERT INTO `sources` VALUES (55,'buffalo','University at Buffalo',1,'buffalo');
INSERT INTO `sources` VALUES (56,'okstate','Oklahoma State University',1,'okstate');
INSERT INTO `sources` VALUES (57,'txstate','Texas State University',1,'txstate');
INSERT INTO `sources` VALUES (58,'temple','Temple University',1,'temple');
INSERT INTO `sources` VALUES (59,'sc','University of South Carolina',1,'sc');
/*!40000 ALTER TABLE `sources` ENABLE KEYS */;
UNLOCK TABLES;
