USE ht;
LOCK TABLES `ht_institutions` WRITE;
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('abac', 'Abraham Baldwin Agricultural College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('allegheny', 'Allegheny College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('amherst', 'Amherst College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('anu', 'Australian National University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('aol', 'AOL');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('archive', 'Internet Archive');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('arizona', 'University of Arizona');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('asu', 'Arizona State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('asurams', 'Albany State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('aub', 'American University of Beirut');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('auburn', 'Auburn University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('auckland', 'University of Auckland');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('augusta', 'Augusta University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bard', 'Bard College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('baylor', 'Baylor University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bc', 'Boston College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bentley-umich', 'Bentley Historical Library, University of Michigan');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('berkeley', 'University of California, Berkeley');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('binghamton', 'Binghamton University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bowdoin', 'Bowdoin College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('brandeis', 'Brandeis University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('brocku', 'Brock University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('brooklynmuseum', 'Brooklyn Museum');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('brown', 'Brown University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('brynmawr', 'Bryn Mawr College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bu', 'Boston University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('bucknell', 'Bucknell University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('buffalo', 'University At Buffalo, The State University of New York');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('byu', 'Brigham Young University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cam', 'University of Cambridge');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('carleton', 'Carleton College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('carletonu', 'Carleton University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('case', 'Case Western Reserve University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ccga', 'College of Coastal Georgia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cgu', 'Claremont Graduate University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uchicago', 'University of Chicago');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('claremont', 'The Claremont Colleges Services');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('clarkart', 'Sterling and Francine Clark Art Institute');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('clayton', 'Clayton State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('clements-umich', 'William L. Clements Library, University of Michigan');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('clemson', 'Clemson University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cmc', 'Claremont McKenna College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cmich', 'Central Michigan University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cmu', 'Carnegie Mellon University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('colby', 'Colby College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('colorado', 'University of Colorado Boulder');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('columbia', 'Columbia University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('columbusstate', 'Columbus State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('conncoll', 'Connecticut College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cornell', 'Cornell University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('cwu', 'Central Washington University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('daltonstate', 'Dalton State College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('dartmouth', 'Dartmouth College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('davidson', 'Davidson College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('depaul', 'DePaul University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('depauw', 'DePauw University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('dickinson', 'Dickinson College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('duke', 'Duke University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ega', 'East Georgia State College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('elon', 'Elon University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('emory', 'Emory University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('facebook', 'Facebook');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('famu', 'Florida A&amp;M University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fau', 'Florida Atlantic University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fgcu', 'Florida Gulf Coast University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fiu', 'Florida International University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fiu-dev', 'Florida International University - Development IdP');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('floridapoly', 'Florida Polytechnic');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('frick', 'The Frick Collection');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fsu', 'Florida State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fsu-dev', 'Florida State University CAS IdP');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('flbog', 'State University System of Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('fvsu', 'Fort Valley State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gatech', 'Georgia Institute of Technology');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gc-cuny', 'CUNY Graduate School and University Center');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gcsu', 'Georgia College &amp; State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('georgetown', 'Georgetown University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('georgiasouthern', 'Georgia Southern University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('getty', 'Getty Research Institute');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ggc', 'Georgia Gwinnett College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gmu', 'George Mason University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('google', 'Google');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gordonstate', 'Gordon State College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('grinnell', 'Grinnell College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gsu', 'Georgia State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gsw', 'Georgia Southwestern State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('harvard', 'Harvard University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('hathitrust', 'HathiTrust');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('haverford', 'Haverford College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('hawaii', 'University of Hawaii');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('hawaii-test', 'University of Hawaii (Testing)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('hec', 'HEC Montréal');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('highlands', 'Georgia Highlands College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('hmc', 'Harvey Mudd College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('howard', 'Howard University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ht_private', 'Private Donor');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ht_support-microsoft', 'Digitization Support from Microsoft');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('humboldt-old', 'Humboldt State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ias', 'IAS, via Princeton University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('iastate', 'Iowa State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('iu', 'Indiana University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uiowa', 'University of Iowa');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('jhu', 'Johns Hopkins University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('jmu', 'James Madison University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('keio', '慶應義塾大学 (Keio University)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('kennesaw', 'Kennesaw State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('kenyon', 'Kenyon College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('kgi', 'Keck Graduate Institute of Applied Life Sciences');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('knowledgeunlatched', 'Knowledge Unlatched');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ksu', 'Kansas State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ku', 'University of Kansas');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('lafayette', 'Lafayette College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('lehigh', 'Lehigh University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('linkedin', 'LinkedIn');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('live', 'Microsoft');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('loc', 'Library of Congress');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('loc-dev', 'Library of Congress Staging IdP');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('luc', 'Loyola University of Chicago');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('macalester', 'Macalester College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mcgill', 'McGill University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mcmaster', 'McMaster University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mdanderson', 'University of Texas M.D. Anderson Cancer Center');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mga', 'Middle Georgia State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('miami', 'University of Miami');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('milproj-dc-umich', 'Millennium Project');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umn', 'University of Minnesota');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('missouri', 'University of Missouri - Columbia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mit', 'Massachusetts Institute of Technology');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mndigital', 'Minnesota Digital Library');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mnhs', 'Minnesota Historical Society');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('monash', 'Monash University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('montana', 'Montana State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('msstate', 'Mississippi State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('msu', 'Michigan State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('mtholyoke', 'Mount Holyoke College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ncf', 'New College of Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ncl', 'National Central Library');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ncsu', 'North Carolina State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('nd', 'University of Notre Dame');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('neu', 'Northeastern University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('nfb', 'National Federation of the Blind');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('nmsu', 'New Mexico State University - Las Cruces Campus');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('northwestern', 'Northwestern University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('nypl', 'New York Public Library');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('nyu', 'New York University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('odu', 'Old Dominion University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ohio', 'Ohio University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('okstate', 'Oklahoma State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('olemiss', 'University of Mississippi');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('osu', 'The Ohio State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ou', 'University of Oklahoma');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ox', 'University of Oxford');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pfw', 'Purdue University Fort Wayne');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pitt', 'University of Pittsburgh');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pitzer', 'Pitzer College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pomona', 'Pomona College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('press-umich', 'University of Michigan Press');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('princeton', 'Princeton University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('psu', 'Pennsylvania State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ptsem', 'Princeton Theological Seminary');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pugetsound', 'University of Puget Sound');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('purdue', 'Purdue University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('queensu', 'Queen's University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('reed', 'Reed College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('richmond', 'University of Richmond');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('rochester', 'University of Rochester');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('rutgers', 'Rutgers University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ryerson', 'Ryerson University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sandiego', 'University of San Diego');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('savannahstate', 'Savannah State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sc', 'University of South Carolina');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('scrippscollege', 'Scripps College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sfu', 'Simon Fraser University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sgsc', 'South Georgia State College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('shu', 'Seton Hall University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sjsu', 'San Jose State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('smith', 'Smith College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('smu', 'Southern Methodist University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('stanford', 'Stanford University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('swarthmore', 'Swarthmore College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('swmed', 'University of Texas Southwestern Medical Center');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sydney', 'University of Sydney');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('syr', 'Syracuse University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('tamu', 'Texas A&amp;M University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('tcu', 'Texas Christian University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('technicalreports', 'Technical Report Archive &amp; Image Library');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('temple', 'Temple University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('trincoll', 'Trinity College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ttu', 'Texas Tech University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('tufts', 'Tufts University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('tulane', 'Tulane University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('twitter', 'Twitter');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('txstate', 'Texas State University - San Marcos');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ua', 'University of Alabama');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ualberta', 'University of Alberta');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ubc', 'University of British Columbia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uc', 'University of Cincinnati');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucalgary', 'University of Calgary');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucdavis', 'University of California, Davis');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucf', 'University of Central Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uci', 'University of California, Irvine');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucla', 'University of California, Los Angeles');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucla-dev', 'University of California, Los Angeles MFA test');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucm', 'Universidad Complutense de Madrid');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucmerced', 'University of California, Merced');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uconn', 'University of Connecticut');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucop', 'University of California, Office of the President');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucr', 'University of California, Riverside');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucsb', 'University of California, Santa Barbara');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucsc', 'University of California, Santa Cruz');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucsd', 'University of California, San Diego');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ucsf', 'University of California, San Francisco');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('udel', 'University of Delaware');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ufl', 'University of Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uga', 'University of Georgia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uh', 'University of Houston');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uh-new', 'University of Houston');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uic', 'University of Illinois at Chicago');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('illinois', 'University of Illinois at Urbana-Champaign');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uky', 'University of Kentucky');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umanitoba', 'University of Manitoba');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umanitoba-dev', 'University Of Manitoba (Dev)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umass', 'University of Massachusetts Amherst');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umd', 'University of Maryland, College Park');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umdl-umich', 'University of Michigan Library IT, Digital Library Production Service, Digital Conversion Unit');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unc', 'University of North Carolina at Chapel Hill');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unf', 'University of North Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ung', 'University of North Georgia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unh', 'University of New Hampshire');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unimelb', 'University of Melbourne');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('union', 'Union College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('universityofcalifornia', 'University of California');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unl', 'University of Nebraska - Lincoln');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unlv', 'University of Nevada - Las Vegas');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unm', 'University of New Mexico');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unt', 'University of North Texas');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uoguelph', 'University of Guelph');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('umich', 'University of Michigan');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uoregon', 'University of Oregon');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uottawa', 'University of Ottawa');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('upenn', 'University of Pennsylvania');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uq', 'The University of Queensland');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uregina', 'University of Regina');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usask', 'University of Saskatchewan');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usc', 'University of Southern California');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usf', 'University of South Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usg', 'University System of Georgia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usu', 'Utah State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('usupress', 'Utah State University Press');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uta', 'University of Texas at Arlington');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utah', 'University of Utah');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utdallas', 'University of Texas at Dallas');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utep', 'University of Texas at El Paso');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utexas', 'University of Texas at Austin');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uth', 'University of Texas Health Science Center at Houston');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utk', 'University of Tennessee, Knoxville');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utmb', 'University of Texas Medical Branch At Galveston');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utoronto', 'University of Toronto');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utrgv', 'University of Texas Rio Grande Valley');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('utsa', 'University of Texas at San Antonio');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uuhhs', 'Unitarian Universalist History and Heritage Society');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('virginia', 'University of Virginia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uvm', 'University of Vermont');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uwaterloo', 'University of Waterloo');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uwf', 'University of West Florida');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uwo', 'University of Western Ontario');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uwyo', 'University of Wyoming');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('valdosta', 'Valdosta State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('vanderbilt', 'Vanderbilt University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('vassar', 'Vassar College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('vcu', 'Virginia Commonwealth University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('vt', 'Virginia Tech');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('washington', 'University of Washington');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wayne', 'Wayne State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wellesley', 'Wellesley College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wesleyan', 'Wesleyan University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('westga', 'University of West Georgia');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wfu', 'Wake Forest University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('whitman', 'Whitman College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wichita', 'Wichita State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('willamette', 'Willamette University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('williams', 'Williams College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wisc', 'University of Wisconsin - Madison');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wlu-ca', 'Wilfrid Laurier University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wlu-edu', 'Washington and Lee University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wm', 'William &amp; Mary');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wooster', 'The College of Wooster');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wpi', 'Worcester Polytechnic Institute');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wsu', 'Washington State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wustl', 'Washington University in St. Louis');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wvu', 'West Virginia University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('xula', 'Xavier University of Louisiana');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('yahoo', 'Yahoo!');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('yale', 'Yale University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('yorku', 'York University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uri', 'University of Rhode Island');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('si', 'Smithsonian Institution');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wwu', 'Western Washington University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('trentu', 'Trent University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('northwestern-dev', 'Northwestern University (Test IdP)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('beloit', 'Beloit College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('westpoint', 'United States Military Academy at West Point');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gvsu', 'Grand Valley State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('eckerd', 'Eckerd College');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('oregonstate', 'Oregon State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('gwu', 'The George Washington University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('liberty', 'Liberty University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('sdsu', 'San Diego State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uga-openathens', 'University of Georgia (via OpenAthens)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('ubc-openathens', 'University of British Columbia Library OpenAthens (UBC)');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uct', 'University of Cape Town');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('simmons', 'Simmons University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('vcccd', 'Ventura County Community College District');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('unomaha', 'University of Nebraska at Omaha');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('humboldt', 'Humboldt State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('missouristate', 'Missouri State University Libraries');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('uark', 'University of Arkansas');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('drake', 'Drake University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('kent', 'Kent State University');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('pratt', 'Pratt Institute');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('wits', 'University of the Witwatersrand, Johannesburg');
INSERT INTO `ht_institutions` (inst_id, name) VALUES ('aucegypt', 'The American University in Cairo');             
UNLOCK TABLES;
