USE ht;
LOCK TABLES `ht_institutions` WRITE;


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;
/*!40103 SET @OLD_TIME_ZONE=@@TIME_ZONE */;
/*!40103 SET TIME_ZONE='+00:00' */;
/*!40014 SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0 */;
/*!40014 SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0 */;
/*!40101 SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='NO_AUTO_VALUE_ON_ZERO' */;
/*!40111 SET @OLD_SQL_NOTES=@@SQL_NOTES, SQL_NOTES=0 */;


LOCK TABLES `ht_institutions` WRITE;
/*!40000 ALTER TABLE `ht_institutions` DISABLE KEYS */;
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('abac', 'Abraham Baldwin Agricultural College', 'abac.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('allegheny', 'Allegheny College', 'allegheny.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('american', 'American University Library (Washington, DC)', 'american.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('amherst', 'Amherst College', 'amherst.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('aol', 'AOL', 'aol.com', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('archive', 'Internet Archive', 'archive.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('arizona', 'University of Arizona', 'arizona.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('asu', 'Arizona State University', 'asu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('asurams', 'Albany State University', 'asurams.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('aub', 'American University of Beirut - الجامعة الأميركيّة في بيروت', 'aub.edu.lb', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('auburn', 'Auburn University', 'auburn.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('augusta', 'Augusta University', 'augusta.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bard', 'Bard College', 'bard.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('baylor', 'Baylor University', 'baylor.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bc', 'Boston College', 'bc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bentley-umich', 'Bentley Historical Library, University of Michigan', 'bentley.umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('berkeley', 'University of California, Berkeley', 'berkeley.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('binghamton', 'Binghamton University', 'binghamton.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('boisestate', 'Boise State University', 'boisestate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bowdoin', 'Bowdoin College', 'bowdoin.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('brandeis', 'Brandeis University', 'brandeis.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('brocku', 'Brock University', 'brocku.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('brooklynmuseum', 'Brooklyn Museum', 'brooklynmuseum.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('brown', 'Brown University', 'brown.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('brynmawr', 'Bryn Mawr College', 'brynmawr.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bu', 'Boston University', 'bu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('bucknell', 'Bucknell University', 'bucknell.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('buffalo', 'University At Buffalo, The State University of New York', 'buffalo.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('byu', 'Brigham Young University', 'byu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cam', 'University of Cambridge', 'cam.ac.uk', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('carleton', 'Carleton College', 'carleton.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('carletonu', 'Carleton University', 'carleton.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('case', 'Case Western Reserve University', 'case.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ccga', 'College of Coastal Georgia', 'ccga.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cgu', 'Claremont Graduate University', 'cgu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('claremont', 'The Claremont Colleges Services', 'claremont.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('clarkart', 'Sterling and Francine Clark Art Institute', 'clarkart.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('clarku', 'Clark University', 'clarku.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('clayton', 'Clayton State University', 'clayton.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('clements-umich', 'William L. Clements Library, University of Michigan', 'clements.umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('clemson', 'Clemson University', 'clemson.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cmc', 'Claremont McKenna College', 'cmc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cmich', 'Central Michigan University', 'cmich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cmu', 'Carnegie Mellon University', 'cmu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('colby', 'Colby College', 'colby.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('colorado', 'University of Colorado Boulder', 'colorado.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('colostate', 'Colorado State University', 'colostate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('columbia', 'Columbia University', 'columbia.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('columbusstate', 'Columbus State University', 'columbusstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('conncoll', 'Connecticut College', 'conncoll.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cornell', 'Cornell University', 'cornell.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cua', 'Catholic University of America', 'cua.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('cwu', 'Central Washington University', 'cwu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('daltonstate', 'Dalton State College', 'daltonstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('dartmouth', 'Dartmouth College', 'dartmouth.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('davidson', 'Davidson College', 'davidson.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('denison', 'Denison University', 'denison.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('depaul', 'DePaul University', 'depaul.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('depauw', 'DePauw University', 'depauw.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('dickinson', 'Dickinson College', 'dickinson.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('drake', 'Drake University', 'drake.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('drexel', 'Drexel University', 'drexel.edu', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('duke', 'Duke University', 'duke.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('eckerd', 'Eckerd College', 'eckerd.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('eduhk', 'Education University of Hong Kong', 'eduhk.hk', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ega', 'East Georgia State College', 'ega.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('elon', 'Elon University', 'elon.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('emory', 'Emory University', 'emory.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('facebook', 'Facebook', 'facebook.com', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('famu', 'Florida A&amp;M University', 'famu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fandm', 'Franklin &amp; Marshall College', 'fandm.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fau', 'Florida Atlantic University', 'fau.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fgcu', 'Florida Gulf Coast University', 'fgcu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fiu', 'Florida International University', 'fiu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fiu-dev', 'Florida International University - Development IdP', 'fiu.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('flbog', 'State University System of Florida', 'flbog.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('floridapoly', 'Florida Polytechnic', 'floridapoly.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('frick', 'The Frick Collection', 'frick.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fsu', 'Florida State University', 'fsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fsu-dev', 'Florida State University CAS IdP', 'fsu.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('fvsu', 'Fort Valley State University', 'fvsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gatech', 'Georgia Institute of Technology', 'gatech.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gc-cuny', 'CUNY Graduate School and University Center', 'gc.cuny.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gcsu', 'Georgia College &amp; State University', 'gcsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('georgetown', 'Georgetown University', 'georgetown.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('georgiasouthern', 'Georgia Southern University', 'georgiasouthern.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('getty', 'Getty Research Institute', 'getty.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ggc', 'Georgia Gwinnett College', 'ggc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gmu', 'George Mason University', 'gmu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('google', 'Google', 'google.com', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gordonstate', 'Gordon State College', 'gordonstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('grinnell', 'Grinnell College', 'grinnell.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gsu', 'Georgia State University', 'gsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gsw', 'Georgia Southwestern State University', 'gsw.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gvsu', 'Grand Valley State University', 'gvsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('gwu', 'The George Washington University', 'gwu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('harvard', 'Harvard University', 'harvard.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hathitrust', 'HathiTrust', 'hathitrust.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('haverford', 'Haverford College', 'haverford.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hawaii', 'University of Hawaii', 'hawaii.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hawaii-test', 'University of Hawaii (Testing)', 'hawaii.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hec', 'HEC Montréal', 'hec.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('highlands', 'Georgia Highlands College', 'highlands.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hmc', 'Harvey Mudd College', 'hmc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('hofstra', 'Hofstra University', 'hofstra.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('howard', 'Howard University', 'howard.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ht_private', 'Private Donor', '', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ht_support-microsoft', 'Digitization Support from Microsoft', '', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('humboldt', 'Humboldt State University', 'humboldt.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('humboldt-old', 'Humboldt State University', 'humboldt.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ias', 'IAS, via Princeton University', 'ias.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('iastate', 'Iowa State University', 'iastate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('illinois', 'University of Illinois at Urbana-Champaign', 'illinois.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('iu', 'Indiana University', 'iu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('jhu', 'Johns Hopkins University', 'jhu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('jmu', 'James Madison University', 'jmu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('keio', 'Keio University 慶應義塾大学 ', 'keio.ac.jp', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('kennesaw', 'Kennesaw State University', 'kennesaw.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('kent', 'Kent State University', 'kent.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('kenyon', 'Kenyon College', 'kenyon.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('kgi', 'Keck Graduate Institute of Applied Life Sciences', 'kgi.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('knowledgeunlatched', 'Knowledge Unlatched', 'knowledgeunlatched.org', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ksu', 'Kansas State University', 'ksu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ku', 'University of Kansas', 'ku.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('lafayette', 'Lafayette College', 'lafayette.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('lehigh', 'Lehigh University', 'lehigh.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('liberty', 'Liberty University', 'liberty.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('linkedin', 'LinkedIn', 'linkedin.com', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('live', 'Microsoft', 'live.com', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('loc', 'Library of Congress', 'loc.gov', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('loc-dev', 'Library of Congress Staging IdP', 'loc.gov', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('luc', 'Loyola University of Chicago', 'luc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('macalester', 'Macalester College', 'macalester.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mcgill', 'McGill University', 'mcgill.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mcmaster', 'McMaster University', 'mcmaster.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mdanderson', 'University of Texas M.D. Anderson Cancer Center', 'mdanderson.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mga', 'Middle Georgia State University', 'mga.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('miami', 'University of Miami', 'miami.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('milproj-dc-umich', 'Millennium Project', 'milproj.dc.umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('missouri', 'University of Missouri - Columbia', 'missouri.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('missouristate', 'Missouri State University Libraries', 'missouristate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mit', 'Massachusetts Institute of Technology', 'mit.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mndigital', 'Minnesota Digital Library', 'mndigital.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mnhs', 'Minnesota Historical Society', 'mnhs.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('monash', 'Monash University', 'monash.edu', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('montana', 'Montana State University', 'montana.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('msstate', 'Mississippi State University', 'msstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('msu', 'Michigan State University', 'msu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mtholyoke', 'Mount Holyoke College', 'mtholyoke.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('mun', 'Memorial University of Newfoundland', 'mun.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('muohio', 'Miami University', 'muohio.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ncf', 'New College of Florida', 'ncf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ncl', 'National Central Library', 'ncl.edu.tw', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ncsu', 'North Carolina State University', 'ncsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('nd', 'University of Notre Dame', 'nd.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('neu', 'Northeastern University', 'neu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('nfb', 'National Federation of the Blind', 'nfb.org', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('nmsu', 'New Mexico State University - Las Cruces Campus', 'nmsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('northwestern', 'Northwestern University', 'northwestern.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('northwestern-dev', 'Northwestern University (Test IdP)', 'northwestern.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('nypl', 'New York Public Library', 'nypl.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('nyu', 'New York University', 'nyu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('oberlin', 'Oberlin College and Conservatory', 'oberlin.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('odu', 'Old Dominion University', 'odu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ohio', 'Ohio University', 'ohio.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('okstate', 'Oklahoma State University', 'okstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('olemiss', 'University of Mississippi', 'olemiss.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('oregonstate', 'Oregon State University', 'oregonstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('osu', 'The Ohio State University', 'osu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ou', 'University of Oklahoma', 'ou.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ox', 'University of Oxford', 'ox.ac.uk', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('oxy', 'Occidental College', 'oxy.edu', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pdx', 'Portland State University', 'pdx.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pfw', 'Purdue University Fort Wayne', 'pfw.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pitt', 'University of Pittsburgh', 'pitt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pitzer', 'Pitzer College', 'pitzer.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pnw', 'Purdue University Northwest', 'pnw.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pomona', 'Pomona College', 'pomona.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pratt', 'Pratt Institute', 'pratt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('press-umich', 'University of Michigan Press', 'press.umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('princeton', 'Princeton University', 'princeton.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('psu', 'Pennsylvania State University', 'psu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ptsem', 'Princeton Theological Seminary', 'ptsem.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('pugetsound', 'University of Puget Sound', 'pugetsound.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('purdue', 'Purdue University Main Campus Libraries', 'purdue.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('purdue-openathens', 'Purdue University (OpenAthens)', 'purdue.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('queensu', "Queen's University", 'queensu.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('reed', 'Reed College', 'reed.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('richmond', 'University of Richmond', 'richmond.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('rochester', 'University of Rochester', 'rochester.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('rutgers', 'Rutgers University', 'rutgers.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sandiego', 'University of San Diego', 'sandiego.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('savannahstate', 'Savannah State University', 'savannahstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sc', 'University of South Carolina', 'sc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('scrippscollege', 'Scripps College', 'scrippscollege.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sdsu', 'San Diego State University', 'sdsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sfu', 'Simon Fraser University', 'sfu.ca', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sgsc', 'South Georgia State College', 'sgsc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('shu', 'Seton Hall University', 'shu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('si', 'Smithsonian Institution', 'si.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('simmons', 'Simmons University', 'simmons.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sjsu', 'San Jose State University', 'sjsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('smith', 'Smith College', 'smith.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('smu', 'Southern Methodist University', 'smu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('stanford', 'Stanford University', 'stanford.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('stonybrook', 'Stony Brook University', 'stonybrook.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('swarthmore', 'Swarthmore College', 'swarthmore.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('swmed', 'University of Texas Southwestern Medical Center', 'swmed.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('sydney', 'University of Sydney', 'sydney.edu.au', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('syr', 'Syracuse University', 'syr.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('tamu', 'Texas A&amp;M University', 'tamu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('tamucc', 'Texas A&amp;M University-Corpus Christi', 'tamucc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('tcu', 'Texas Christian University', 'tcu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('technicalreports', 'Technical Report Archive &amp; Image Library', 'technicalreports.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('temple', 'Temple University', 'temple.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('torontomu', 'Toronto Metropolitan University', 'torontomu.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('trentu', 'Trent University', 'trentu.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('trincoll', 'Trinity College', 'trincoll.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ttu', 'Texas Tech University', 'ttu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('tufts', 'Tufts University', 'tufts.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('tulane', 'Tulane University', 'tulane.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('twitter', 'Twitter', 'twitter.com', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('txstate', 'Texas State University - San Marcos', 'txstate.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ua', 'University of Alabama', 'ua.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ualberta', 'University of Alberta', 'ualberta.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uark', 'University of Arkansas', 'uark.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ubc', 'University of British Columbia', 'ubc.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ubc-openathens', 'University of British Columbia Library OpenAthens (UBC)', 'ubc.ca', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uc', 'University of Cincinnati', 'uc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucalgary', 'University of Calgary', 'ucalgary.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucdavis', 'University of California, Davis', 'ucdavis.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucf', 'University of Central Florida', 'ucf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uchicago', 'University of Chicago', 'uchicago.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uci', 'University of California, Irvine', 'uci.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucla', 'University of California, Los Angeles', 'ucla.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucla-dev', 'University of California, Los Angeles MFA test', 'ucla.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucm', 'Universidad Complutense de Madrid', 'ucm.es', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucmerced', 'University of California, Merced', 'ucmerced.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uconn', 'University of Connecticut', 'uconn.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uconn-cas', 'UConn CAS SSO', 'uconn.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucop', 'University of California, Office of the President', 'ucop.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucr', 'University of California, Riverside', 'ucr.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucsb', 'University of California, Santa Barbara', 'ucsb.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucsc', 'University of California, Santa Cruz', 'ucsc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucsd', 'University of California, San Diego', 'ucsd.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ucsf', 'University of California, San Francisco', 'ucsf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uct', 'University of Cape Town', 'uct.ac.za', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('udel', 'University of Delaware', 'udel.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ufl', 'University of Florida', 'ufl.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uga', 'University of Georgia', 'uga.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uga-openathens', 'University of Georgia (via OpenAthens)', 'uga.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uh', 'University of Houston', 'lib.uh.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uh-new', 'University of Houston', 'uh.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uic', 'University of Illinois Chicago', 'uic.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uiowa', 'University of Iowa', 'uiowa.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uky', 'University of Kentucky', 'uky.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umanitoba', 'University of Manitoba', 'umanitoba.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umanitoba-dev', 'University Of Manitoba (Dev)', 'umanitoba.ca', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umass', 'University of Massachusetts Amherst', 'umass.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umd', 'University of Maryland, College Park', 'umd.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umdl-umich', 'University of Michigan Library IT, Digital Library Production Service, Digital Conversion Unit', 'umdl.umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umich', 'University of Michigan', 'umich.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umn', 'University of Minnesota', 'umn.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umontreal', 'Université de Montréal', 'umontreal.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('umt', 'The University of Montana', 'umt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unc', 'University of North Carolina at Chapel Hill', 'unc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unco', 'University of Northern Colorado', 'unco.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('und', 'University of North Dakota', 'und.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unf', 'University of North Florida', 'unf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('ung', 'University of North Georgia', 'ung.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uni', 'University of Northern Iowa', 'uni.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unimelb', 'University of Melbourne', 'unimelb.edu.au', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('union', 'Union College', 'union.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('universityofcalifornia', 'University of California', 'universityofcalifornia.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unl', 'University of Nebraska - Lincoln', 'unl.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unlv', 'University of Nevada - Las Vegas', 'unlv.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unm', 'University of New Mexico', 'unm.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unomaha', 'University of Nebraska at Omaha', 'unomaha.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('unt', 'University of North Texas', 'unt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uoguelph', 'University of Guelph', 'uoguelph.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uoregon', 'University of Oregon', 'uoregon.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uottawa', 'University of Ottawa', 'uottawa.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('upenn', 'University of Pennsylvania', 'upenn.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uq', 'The University of Queensland', 'uq.edu.au', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uregina', 'University of Regina', 'uregina.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uri', 'University of Rhode Island', 'uri.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usask', 'University of Saskatchewan', 'usask.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usc', 'University of Southern California', 'usc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usf', 'University of South Florida', 'usf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usg', 'University System of Georgia', 'usg.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usnh', 'University System of New Hampshire', 'usnh.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usu', 'Utah State University', 'usu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('usupress', 'Utah State University Press', 'usupress.com', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uta', 'University of Texas at Arlington', 'uta.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utah', 'University of Utah', 'utah.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utdallas', 'University of Texas at Dallas', 'utdallas.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utep', 'University of Texas at El Paso', 'utep.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utexas', 'University of Texas at Austin', 'utexas.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uth', 'University of Texas Health Science Center at Houston', 'uth.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utk', 'University of Tennessee, Knoxville', 'utk.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utmb', 'University of Texas Medical Branch At Galveston', 'utmb.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utoronto', 'University of Toronto', 'utoronto.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utrgv', 'University of Texas Rio Grande Valley', 'utrgv.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utsa', 'University of Texas at San Antonio', 'utsa.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('utulsa', 'The University Of Tulsa', 'utulsa.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uuhhs', 'Unitarian Universalist History and Heritage Society', 'uuhhs.org', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uvm', 'University of Vermont', 'uvm.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uwaterloo', 'University of Waterloo', 'uwaterloo.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uwf', 'University of West Florida', 'uwf.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uwo', 'University of Western Ontario', 'uwo.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('uwyo', 'University of Wyoming', 'uwyo.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('valdosta', 'Valdosta State University', 'valdosta.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('vanderbilt', 'Vanderbilt University', 'vanderbilt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('vassar', 'Vassar College', 'vassar.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('vcccd', 'Ventura County Community College District', 'vcccd.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('vcu', 'Virginia Commonwealth University', 'vcu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('villanova', 'Villanova University', 'villanova.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('virginia', 'University of Virginia', 'virginia.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('vt', 'Virginia Tech', 'vt.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('washington', 'University of Washington', 'washington.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wayne', 'Wayne State University', 'wayne.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wellesley', 'Wellesley College', 'wellesley.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wesleyan', 'Wesleyan University', 'wesleyan.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('westga', 'University of West Georgia', 'westga.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('westpoint', 'United States Military Academy at West Point', 'westpoint.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wfu', 'Wake Forest University', 'wfu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('whitman', 'Whitman College', 'whitman.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wichita', 'Wichita State University', 'wichita.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('willamette', 'Willamette University', 'willamette.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('williams', 'Williams College', 'williams.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wisc', 'University of Wisconsin - Madison', 'wisc.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wlu-ca', 'Wilfrid Laurier University', 'wlu.ca', 0, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wlu-edu', 'Washington and Lee University', 'wlu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wm', 'William &amp; Mary', 'wm.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wooster', 'The College of Wooster', 'wooster.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wpi', 'Worcester Polytechnic Institute', 'wpi.edu', 1, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wsu', 'Washington State University', 'wsu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wustl', 'Washington University in St. Louis', 'wustl.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wvu', 'West Virginia University', 'wvu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('wwu', 'Western Washington University', 'wwu.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('xula', 'Xavier University of Louisiana', 'xula.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('yahoo', 'Yahoo!', 'yahoo.com', 0, 0);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('yale', 'Yale University', 'yale.edu', 1, 1);
INSERT INTO `ht_institutions` (inst_id, name, domain, us, enabled) VALUES ('yorku', 'York University', 'yorku.ca', 0, 1);
/*!40000 ALTER TABLE `ht_institutions` ENABLE KEYS */;
UNLOCK TABLES;
/*!40103 SET TIME_ZONE=@OLD_TIME_ZONE */;

/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

