name: Publish Docker Image
on:
  release:
    types: [published]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    - name: Clone latest repository
      uses: actions/checkout@v2
    - name: Build container image and push to DockerHub
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: 'hathitrust/db-image:latest'
        file: Dockerfile
    - name: Image digest
      run: |
        echo '${{ steps.docker_build.outputs.digest }}'
