name: Run Tests

on:
    push:
        branches:
            - main
    pull_request:

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Run Tests
              run: |
                docker compose up -d
                # docker compose exec mariadb healthcheck.sh --su-mysql --connect --innodb_initialized
                docker compose down